spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=client_db;encrypt=true;trustServerCertificate=true;
    username: sa
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
